#!/usr/bin/env node
/**
 * Writes sample cycle markdown under logs/ — no API keys, no Gemini.
 * Run from repo root: npm run agentic:dry-run
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const agenticRoot = path.resolve(__dirname, "..");
const dept = "publishing";
const outDir = path.join(agenticRoot, "logs", dept);
const outFile = path.join(outDir, "cycle-1.md");

const body = `# Publishing — Cycle 1
**Date:** ${new Date().toISOString().slice(0, 10)}
**Agent Role:** Worker
**Task Type:** Article

## Input
<!-- What was given to the agent -->
Sample keyword: \`automotive SEO basics\` (dry-run — no API)

## Output
<!-- What the agent produced -->
_Stub: run \`npm run agentic:dry-run\` after Phase 1 skeleton. No Gemini call._

## Manager Decision
- [ ] Approved
- [ ] Rejected
**Reason:** _n/a — template only_

## Notes
Generated by \`xalura-agentic/scripts/dry-run.mjs\` (Phase 1).
`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, body, "utf8");
console.log(`Wrote ${path.relative(process.cwd(), outFile)}`);
