/** Long-form sample draft for the writer live panel (~500 words, loops). */
export const MOCHI_MANUSCRIPT = `When the check engine light comes on, most drivers feel the same quiet dread. It could mean nothing serious, or it could mean a repair bill that reshapes the month. The light is not a verdict; it is a pointer. Modern engines wrap dozens of sensors in a conversation the car is always having with itself. Oxygen sensors watch exhaust chemistry. Knock sensors listen for detonation that should not be there. The powertrain control module compares what should happen to what is actually happening, hundreds of times per second.

A misfire code does not always mean a bad spark plug. It can mean a weak coil, contaminated fuel, a vacuum leak leaning out a cylinder, or even a wiring fault that only appears when the harness flexes in cold weather. That is why a single code rarely tells the whole story. Context matters: mileage, maintenance history, whether the problem appears at idle or under load, and whether the smell of fuel or oil has changed. A thoughtful diagnosis starts with patterns, not panic.

Symptoms are evidence. A rough idle that smooths out when the engine warms suggests different causes than a rough idle that gets worse. A sulfur smell near the catalytic converter area invites questions about fuel trim and converter efficiency. A flashing check engine light during acceleration is not something to ignore on a long trip; it often signals raw fuel entering the catalyst in a way that can overheat it.

Parts catalogs are full of look-alike components that do not behave alike. Sensors have calibration ranges. Aftermarket replacements sometimes need a relearn procedure. Torque specifications exist because clamp load affects seal surfaces and heat paths. Skipping the small steps is how good intentions turn into repeat failures.

The goal of a guide like this is not to replace a professional technician. It is to help you understand what questions to ask, what descriptions to offer, and what timelines might be reasonable. Cars are systems. When you treat them that way, the light on the dash becomes less like a verdict and more like a sentence you can finish with good information.

Seasonal changes matter too. Rubber hoses stiffen, battery capacity drops, and short trips never let the catalyst reach the temperature window where it cleans most efficiently. If you only drive five minutes at a time, you may see more moisture in the oil and more deposits in places that expect heat cycles. Longer drives are not just good for the battery; they are part of how the emissions system proves itself. Keep notes when something changes: a new sound after a fill-up, a new vibration after a curb strike, a new smell after a long grade. Those details turn a vague problem into a traceable one, and they are the same details a good shop will want anyway. Small habits like that save time, money, and a lot of unnecessary worry.`;
