/**
 * OpenNext entry: reuse generated `fetch`, add **scheduled** crons (hourly incremental, 10m Chief sweep, 2h legacy publish).
 * Build must run first so `.open-next/worker.js` exists (`npm run build`).
 */
// @ts-expect-error — generated by `opennextjs-cloudflare build`
import { default as generated } from "../.open-next/worker.js";

const handler = generated as { fetch: (request: Request, env: Record<string, unknown>, ctx: { waitUntil(p: Promise<unknown>): void }) => Response | Promise<Response> };

function pickEnv(env: Record<string, unknown>, key: string): string | undefined {
  const v = env[key];
  if (typeof v === "string" && v.trim()) return v.trim();
  const p =
    typeof process !== "undefined" && process.env
      ? (process.env[key] as string | undefined)
      : undefined;
  return typeof p === "string" && p.trim() ? p.trim() : undefined;
}

export default {
  fetch: handler.fetch,

  scheduled(
    _event: { cron: string; scheduledTime: number },
    env: Record<string, unknown>,
    ctx: { waitUntil(p: Promise<unknown>): void },
  ): void {
    ctx.waitUntil(
      (async () => {
        const base =
          pickEnv(env, "AGENTIC_CRON_BASE_URL") ||
          pickEnv(env, "AGENTIC_PUBLIC_BASE_URL") ||
          pickEnv(env, "NEXT_PUBLIC_SITE_URL");
        const secret = pickEnv(env, "AGENTIC_CRON_SECRET");
        if (!base || !secret) {
          console.warn(
            "[cron:agentic] skipped — set AGENTIC_CRON_BASE_URL (or AGENTIC_PUBLIC_BASE_URL / NEXT_PUBLIC_SITE_URL) and AGENTIC_CRON_SECRET on the Worker",
          );
          return;
        }
        const cron = _event.cron?.trim() ?? "";
        let path = "/api/cron/agentic-publish";
        if (cron === "0 * * * *") path = "/api/cron/agentic-incremental";
        else if (cron === "*/10 * * * *") path = "/api/cron/agentic-chief-sweep";
        const url = `${base.replace(/\/$/, "")}${path}`;
        try {
          const res = await fetch(url, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${secret}`,
            },
            body: "{}",
          });
          const text = await res.text();
          if (!res.ok) {
            console.warn("[cron:agentic] HTTP", cron || path, res.status, text.slice(0, 800));
          } else {
            console.log("[cron:agentic] ok", cron || path, res.status, text.slice(0, 400));
          }
        } catch (e) {
          console.error("[cron:agentic] fetch error", e);
        }
      })(),
    );
  },
};
